// Category search
export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
export const FETCH_CATEGORIES_FULFILLED = 'FETCH_CATEGORIES_FULFILLED';
export const FETCH_CATEGORIES_REJECTED = 'FETCH_CATEGORIES_REJECTED';
export const SET_CATEGORY = 'SET_CATEGORY';
export const SEARCH_CATEGORY = 'SEARCH_CATEGORY';

export const FETCH_RESOURCES = 'REQUEST_RESOURCES';
export const FETCH_RESOURCES_FULFILLED = 'FETCH_RESOURCES_FULFILLED';
export const FETCH_RESOURCES_REJECTED = 'FETCH_RESOURCES_REJECTED';
export const FETCH_RESOURCE = 'REQUEST_RESOURCE';
export const FETCH_RESOURCE_FULFILLED = 'FETCH_RESOURCE_FULFILLED';
export const FETCH_RESOURCE_REJECTED = 'FETCH_RESOURCE_REJECTED';
export const SET_RESOURCE = 'SET_RESOURCE';

export const GET_USER_LOCATION = 'GET_USER_LOCATION';
export const GET_USER_LOCATION_FULFILLED = 'GET_USER_LOCATION_FULFILLED';
export const GET_USER_LOCATION_ERROR = 'GET_USER_LOCATION_ERROR';
export const UPDATE_USER_LOCATION = 'UPDATE_USER_LOCATION';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
