// Category search
export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
export const FETCH_CATEGORIES_FULFILLED = 'FETCH_CATEGORIES_FULFILLED';
export const FETCH_CATEGORIES_REJECTED = 'FETCH_CATEGORIES_REJECTED';
export const SET_CATEGORY = 'SET_CATEGORY';
export const SEARCH_CATEGORY = 'SEARCH_CATEGORY';

export const FETCH_RESOURCES = 'REQUEST_RESOURCES';
export const FETCH_RESOURCES_FULFILLED = 'FETCH_RESOURCES_FULFILLED';
export const FETCH_RESOURCES_REJECTED = 'FETCH_RESOURCES_REJECTED';
export const SET_RESOURCE = 'SET_RESOURCE';

export const GET_USER_LOCATION = 'GET_USER_LOCATION';
