// Category search
export const GET_CATEGORIES = 'GET_CATEGORIES';
export const SEARCH_CATEGORY = 'SEARCH_CATEGORY';
export const LOAD_RESOURCES_BY_CATEGORY = 'LOAD_RESOURCES_BY_CATEGORY';
export const GET_USER_LOCATION = 'GET_USER_LOCATION';

